name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ajadi15augst

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "dfa40f6a-4dbd-4ab5-b3b3-59fd4aaf47c5" \
            --password "fUx8Q~Z7uDdxp-loUIBXMhf.S3y3gPCEDHRdDcc." \
            --tenant "71de1bb5-ad71-4d44-947d-ea6848c11e93"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "fc4ff682-f59a-49fa-afe4-086f6b5ac324"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    # Apply ONLY after push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: ajadi15augst

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "dfa40f6a-4dbd-4ab5-b3b3-59fd4aaf47c5" \
            --password "fUx8Q~Z7uDdxp-loUIBXMhf.S3y3gPCEDHRdDcc." \
            --tenant "71de1bb5-ad71-4d44-947d-ea6848c11e93"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "fc4ff682-f59a-49fa-afe4-086f6b5ac324"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan